CREATE TYPE "user_role" AS ENUM (
  'customer',
  'seller',
  'admin',
  'store_owner',
  'support'
);

CREATE TYPE "seller_status" AS ENUM (
  'pending',
  'approved',
  'suspended',
  'rejected'
);

CREATE TYPE "product_status" AS ENUM (
  'draft',
  'active',
  'inactive',
  'rejected'
);

CREATE TYPE "order_status" AS ENUM (
  'pending',
  'confirmed',
  'processing',
  'shipped',
  'partially_delivered',
  'delivered',
  'cancelled',
  'refunded',
  'completed'
);

CREATE TYPE "order_item_status" AS ENUM (
  'pending',
  'confirmed',
  'processing',
  'shipped',
  'delivered',
  'cancelled',
  'returned',
  'refunded'
);

CREATE TYPE "shipment_status" AS ENUM (
  'pending',
  'processing',
  'shipped',
  'in_transit',
  'delivered',
  'cancelled',
  'returned'
);

CREATE TYPE "payment_status" AS ENUM (
  'pending',
  'authorized',
  'paid',
  'failed',
  'cancelled',
  'refunded',
  'partially_refunded'
);

CREATE TYPE "payment_method" AS ENUM (
  'cash_on_delivery',
  'card',
  'paypal',
  'instapay'
);

CREATE TYPE "coupon_discount_type" AS ENUM (
  'percentage',
  'fixed'
);

CREATE TYPE "prescription_status" AS ENUM (
  'pending',
  'approved',
  'rejected',
  'expired'
);

CREATE TYPE "return_status" AS ENUM (
  'requested',
  'approved',
  'rejected',
  'received',
  'refunded',
  'cancelled'
);

CREATE TYPE "ticket_status" AS ENUM (
  'open',
  'in_progress',
  'resolved',
  'closed'
);

CREATE TYPE "page_status" AS ENUM (
  'draft',
  'published',
  'archived'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "phone" varchar(50),
  "password_hash" varchar(255) NOT NULL,
  "role" user_role NOT NULL DEFAULT 'customer',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "seller_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "business_name" varchar(255) NOT NULL,
  "status" seller_status NOT NULL DEFAULT 'pending',
  "approved_by" integer,
  "approved_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "city" varchar(100) NOT NULL,
  "area" varchar(100),
  "street" varchar(255),
  "building" varchar(100),
  "apartment" varchar(100),
  "postal_code" varchar(30),
  "phone" varchar(50) NOT NULL,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" integer,
  "name" varchar(255) NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "brands" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  "brand_id" integer,
  "name" varchar(255) NOT NULL,
  "description" text,
  "sku" varchar(100),
  "requires_prescription" boolean NOT NULL DEFAULT false,
  "status" product_status NOT NULL DEFAULT 'draft',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "product_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "variant_id" integer,
  "url" varchar(1000) NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_primary" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "product_attributes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "name" varchar(100) NOT NULL
);

CREATE TABLE "product_attribute_values" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attribute_id" integer NOT NULL,
  "value" varchar(255) NOT NULL
);

CREATE TABLE "product_variants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "label" varchar(255),
  "price" decimal(12,2) NOT NULL,
  "compare_at_price" decimal(12,2),
  "sku" varchar(100) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "variant_attribute_values" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "variant_id" integer NOT NULL,
  "attribute_value_id" integer NOT NULL
);

CREATE TABLE "inventory_batches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "variant_id" integer NOT NULL,
  "batch_number" varchar(100),
  "expiry_date" date,
  "quantity_received" integer NOT NULL DEFAULT 0,
  "quantity_available" integer NOT NULL DEFAULT 0,
  "quantity_reserved" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "inventory_transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "variant_id" integer NOT NULL,
  "inventory_batch_id" integer,
  "quantity" integer NOT NULL,
  "transaction_type" varchar(50) NOT NULL,
  "reference_type" varchar(50),
  "reference_id" integer,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "carts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "cart_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" integer NOT NULL,
  "variant_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "wishlists" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "wishlist_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wishlist_id" integer NOT NULL,
  "variant_id" integer NOT NULL,
  "added_at" timestamp NOT NULL
);

CREATE TABLE "prescriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "seller_id" integer,
  "image_url" varchar(1000) NOT NULL,
  "status" prescription_status NOT NULL DEFAULT 'pending',
  "reviewed_by" integer,
  "reviewed_at" timestamp,
  "expires_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "coupon_id" integer,
  "status" order_status NOT NULL DEFAULT 'pending',
  "subtotal" decimal(12,2) NOT NULL DEFAULT 0,
  "discount_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "shipping_fee" decimal(12,2) NOT NULL DEFAULT 0,
  "tax_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "cancelled_at" timestamp,
  "completed_at" timestamp
);

CREATE TABLE "order_shipping_addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer UNIQUE NOT NULL,
  "recipient_name" varchar(255) NOT NULL,
  "phone" varchar(50) NOT NULL,
  "city" varchar(100) NOT NULL,
  "area" varchar(100),
  "street" varchar(255),
  "building" varchar(100),
  "apartment" varchar(100),
  "postal_code" varchar(30),
  "created_at" timestamp NOT NULL
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "variant_id" integer NOT NULL,
  "seller_id" integer NOT NULL,
  "shipment_id" integer,
  "prescription_id" integer,
  "quantity" integer NOT NULL,
  "price_at_purchase" decimal(12,2) NOT NULL,
  "discount_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "tax_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL,
  "item_status" order_item_status NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "order_item_batch_allocations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_item_id" integer NOT NULL,
  "inventory_batch_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "shipments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "seller_id" integer NOT NULL,
  "carrier" varchar(100),
  "tracking_number" varchar(255),
  "status" shipment_status NOT NULL DEFAULT 'pending',
  "shipping_fee" decimal(12,2) NOT NULL DEFAULT 0,
  "shipped_at" timestamp,
  "delivered_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "method" payment_method NOT NULL,
  "status" payment_status NOT NULL DEFAULT 'pending',
  "amount" decimal(12,2) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'EGP',
  "provider" varchar(100),
  "transaction_ref" varchar(255),
  "failure_reason" text,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "paid_at" timestamp,
  "refunded_at" timestamp
);

CREATE TABLE "coupons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(100) UNIQUE NOT NULL,
  "discount_type" coupon_discount_type NOT NULL,
  "discount_value" decimal(12,2) NOT NULL,
  "min_order_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "max_discount_amount" decimal(12,2),
  "max_uses" integer,
  "max_uses_per_user" integer,
  "valid_from" timestamp NOT NULL,
  "valid_until" timestamp NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "coupon_usages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "coupon_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "order_id" integer UNIQUE NOT NULL,
  "used_at" timestamp NOT NULL
);

CREATE TABLE "return_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_item_id" integer NOT NULL,
  "reason" text NOT NULL,
  "status" return_status NOT NULL DEFAULT 'requested',
  "requested_at" timestamp NOT NULL,
  "deadline" timestamp,
  "approved_at" timestamp,
  "received_at" timestamp,
  "refunded_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "product_reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "order_id" integer NOT NULL,
  "rating" integer NOT NULL,
  "comment" text,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "seller_reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "order_id" integer NOT NULL,
  "rating" integer NOT NULL,
  "comment" text,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "support_tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "subject" varchar(255) NOT NULL,
  "status" ticket_status NOT NULL DEFAULT 'open',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "closed_at" timestamp
);

CREATE TABLE "support_messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" integer NOT NULL,
  "sender_id" integer NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "pages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" varchar(255) UNIQUE NOT NULL,
  "title" varchar(255) NOT NULL,
  "content" text,
  "status" page_status NOT NULL DEFAULT 'draft',
  "updated_by" integer,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE INDEX ON "users" ("role");

CREATE INDEX ON "users" ("phone");

CREATE INDEX ON "seller_profiles" ("status");

CREATE INDEX ON "seller_profiles" ("approved_by");

CREATE INDEX ON "addresses" ("user_id");

CREATE INDEX ON "categories" ("parent_id");

CREATE UNIQUE INDEX ON "categories" ("parent_id", "name");

CREATE INDEX ON "products" ("seller_id");

CREATE INDEX ON "products" ("category_id");

CREATE INDEX ON "products" ("brand_id");

CREATE INDEX ON "products" ("status");

CREATE UNIQUE INDEX ON "products" ("seller_id", "sku");

CREATE INDEX ON "product_images" ("product_id");

CREATE INDEX ON "product_images" ("variant_id");

CREATE INDEX ON "product_images" ("product_id", "sort_order");

CREATE UNIQUE INDEX ON "product_attributes" ("product_id", "name");

CREATE UNIQUE INDEX ON "product_attribute_values" ("attribute_id", "value");

CREATE UNIQUE INDEX ON "product_variants" ("product_id", "sku");

CREATE UNIQUE INDEX ON "variant_attribute_values" ("variant_id", "attribute_value_id");

CREATE INDEX ON "variant_attribute_values" ("attribute_value_id");

CREATE INDEX ON "inventory_batches" ("variant_id");

CREATE INDEX ON "inventory_batches" ("expiry_date");

CREATE UNIQUE INDEX ON "inventory_batches" ("variant_id", "batch_number");

CREATE INDEX ON "inventory_transactions" ("variant_id");

CREATE INDEX ON "inventory_transactions" ("inventory_batch_id");

CREATE INDEX ON "inventory_transactions" ("reference_type", "reference_id");

CREATE UNIQUE INDEX ON "cart_items" ("cart_id", "variant_id");

CREATE INDEX ON "cart_items" ("variant_id");

CREATE UNIQUE INDEX ON "wishlist_items" ("wishlist_id", "variant_id");

CREATE INDEX ON "wishlist_items" ("variant_id");

CREATE INDEX ON "prescriptions" ("user_id");

CREATE INDEX ON "prescriptions" ("seller_id");

CREATE INDEX ON "prescriptions" ("status");

CREATE INDEX ON "prescriptions" ("reviewed_by");

CREATE INDEX ON "orders" ("user_id");

CREATE INDEX ON "orders" ("coupon_id");

CREATE INDEX ON "orders" ("status");

CREATE INDEX ON "orders" ("created_at");

CREATE INDEX ON "order_items" ("order_id");

CREATE INDEX ON "order_items" ("variant_id");

CREATE INDEX ON "order_items" ("seller_id");

CREATE INDEX ON "order_items" ("shipment_id");

CREATE INDEX ON "order_items" ("prescription_id");

CREATE UNIQUE INDEX ON "order_item_batch_allocations" ("order_item_id", "inventory_batch_id");

CREATE INDEX ON "order_item_batch_allocations" ("inventory_batch_id");

CREATE INDEX ON "shipments" ("status");

CREATE UNIQUE INDEX ON "shipments" ("tracking_number");

CREATE UNIQUE INDEX ON "shipments" ("order_id", "seller_id");

CREATE INDEX ON "payments" ("order_id");

CREATE INDEX ON "payments" ("status");

CREATE UNIQUE INDEX ON "payments" ("transaction_ref");

CREATE INDEX ON "coupons" ("is_active");

CREATE INDEX ON "coupons" ("valid_from");

CREATE INDEX ON "coupons" ("valid_until");

CREATE INDEX ON "coupon_usages" ("coupon_id", "user_id");

CREATE INDEX ON "return_requests" ("order_item_id");

CREATE INDEX ON "return_requests" ("status");

CREATE UNIQUE INDEX ON "product_reviews" ("product_id", "user_id", "order_id");

CREATE UNIQUE INDEX ON "seller_reviews" ("seller_id", "user_id", "order_id");

CREATE INDEX ON "support_tickets" ("user_id");

CREATE INDEX ON "support_tickets" ("status");

CREATE INDEX ON "support_messages" ("ticket_id");

CREATE INDEX ON "pages" ("status");

ALTER TABLE "seller_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seller_profiles" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("seller_id") REFERENCES "seller_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_attributes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_attribute_values" ADD FOREIGN KEY ("attribute_id") REFERENCES "product_attributes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "variant_attribute_values" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "variant_attribute_values" ADD FOREIGN KEY ("attribute_value_id") REFERENCES "product_attribute_values" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_batches" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("inventory_batch_id") REFERENCES "inventory_batches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("wishlist_id") REFERENCES "wishlists" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("seller_id") REFERENCES "seller_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("coupon_id") REFERENCES "coupons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_shipping_addresses" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("seller_id") REFERENCES "seller_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("shipment_id") REFERENCES "shipments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("prescription_id") REFERENCES "prescriptions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item_batch_allocations" ADD FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item_batch_allocations" ADD FOREIGN KEY ("inventory_batch_id") REFERENCES "inventory_batches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shipments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shipments" ADD FOREIGN KEY ("seller_id") REFERENCES "seller_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "coupon_usages" ADD FOREIGN KEY ("coupon_id") REFERENCES "coupons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "coupon_usages" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "coupon_usages" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "return_requests" ADD FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seller_reviews" ADD FOREIGN KEY ("seller_id") REFERENCES "seller_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seller_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seller_reviews" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_tickets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_messages" ADD FOREIGN KEY ("ticket_id") REFERENCES "support_tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pages" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
